import Head from 'next/head'
import { Books } from '@eaj/books';
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Layout from '../components/layout';

export default function HomePage({ list }) {
  return (
    <Layout list={list}>
      <div className={styles.container}>
        <Head>
          <title>Books</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <Link href="/books"><a>Books</a></Link>!
          </h1>
        </main>
      </div>
    </Layout>
    
  )
}

export async function getStaticProps(context) {
  const list = new Books().list;
  return {
    props: {
      list: JSON.parse(JSON.stringify(list))
    },
  }
}
